=== UO289510/sew-25/xml/circuito.dtd
<!ELEMENT circuito (caracteristicas, carrera, referencias, galeria, coordenadas, resultados)>
<!ELEMENT caracteristicas (caracteristica*)>
<!ELEMENT caracteristica (#PCDATA)>

<!ELEMENT carrera (infoCarrera)>
<!ELEMENT infoCarrera (dato+)>
<!ELEMENT dato (#PCDATA)>

<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!ATTLIST caracteristica nombre CDATA #REQUIRED>
<!ATTLIST caracteristica longitud CDATA #REQUIRED>
<!ATTLIST caracteristica anchura CDATA #REQUIRED>
<!ATTLIST caracteristica localidad CDATA #REQUIRED>
<!ATTLIST caracteristica pais CDATA #REQUIRED>

<!ATTLIST dato fecha CDATA #REQUIRED>
<!ATTLIST dato hora CDATA #REQUIRED>
<!ATTLIST dato vueltas CDATA #REQUIRED>
<!ATTLIST dato patrocinador CDATA #REQUIRED>

<!ATTLIST referencia enlace CDATA #REQUIRED>
<!ATTLIST referencia nombre CDATA #REQUIRED>

<!ELEMENT galeria (galeria_imagenes, galeria_videos)>
<!ELEMENT galeria_imagenes (foto+)>
<!ELEMENT foto (#PCDATA)>

<!ELEMENT galeria_videos (video+)>
<!ELEMENT video (#PCDATA)>

<!ATTLIST foto src CDATA #REQUIRED>
<!ATTLIST foto alt CDATA #REQUIRED>
<!ATTLIST video src CDATA #REQUIRED>

<!ELEMENT coordenadas (salida, tramo*)>
<!ELEMENT salida (#PCDATA)>
<!ELEMENT tramo (#PCDATA)>

<!ATTLIST salida latitud_inicio CDATA #REQUIRED>
<!ATTLIST salida longitud_inicio CDATA #REQUIRED>
<!ATTLIST salida altitud_inicio CDATA #REQUIRED>

<!ATTLIST tramo distancia CDATA #REQUIRED>
<!ATTLIST tramo latitud CDATA #REQUIRED>
<!ATTLIST tramo longitud CDATA #REQUIRED>
<!ATTLIST tramo altitud CDATA #REQUIRED>
<!ATTLIST tramo sector CDATA #REQUIRED>

<!ELEMENT resultados (ganador, tiempo, primer_puesto, segundo_puesto, tercer_puesto)>
<!ELEMENT ganador (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT primer_puesto (#PCDATA)>
<!ELEMENT segundo_puesto (#PCDATA)>
<!ELEMENT tercer_puesto (#PCDATA)>

=== UO289510/sew-25/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">

<circuito>
    <caracteristicas>
        <caracteristica nombre="Red Bull Ring Spielberg"
            longitud="4326"
            anchura="13"
            localidad="Spielberg"
            pais="Austria"/>
    </caracteristicas>

    <carrera>
        <infoCarrera>
            <dato fecha="17 de agosto 2025"
            hora="17:00"
            vueltas="28"
            patrocinador="Bwin"/>
        </infoCarrera>
    </carrera>

    <referencias>
        <referencia enlace="https://en.wikipedia.org/wiki/Red_Bull_Ring" nombre="Wikipedia - Circuito Red Bull Ring"/>
        <referencia enlace="https://www.redbullring.com/en/track/red-bull-ring-f1-motogp-track/" nombre="MotoGP - Circuito Red Bull Ring"/>
    </referencias>

    <galeria>
        <galeria_imagenes>
            <foto src="multimedia/circuito.jpg" alt="circuito"/>
        </galeria_imagenes>

        <galeria_videos>
            <video src="multimedia/circuito.mp4" type='video/mp4;codecs="avc1.42E01E, mp4a.40.2"'/>
        </galeria_videos>
    </galeria>

    <coordenadas>
        <salida latitud_inicio="47° 13' 11.85'' N"
        longitud_inicio="14° 45' 53.48'' E"
        altitud_inicio="679"/>

        <!-- Inicio.1 -->
        <tramo distancia="69.60"
                latitud="47° 13' 11.29'' N"
                longitud="14° 45' 50.26'' E"
                altitud="679"
                sector="1"/>

        <!-- Inicio.2 -->
        <tramo distancia="64.21"
                latitud="47° 13' 10.73'' N"
                longitud="14° 45' 47.33'' E"
                altitud="681"
                sector="1"/>

        <!-- Inicio.3 -->
        <tramo distancia="12.00"
                latitud="47° 13' 10.62'' N"
                longitud="14° 45' 46.80'' E"
                altitud="682"
                sector="1"/>

        <!-- Inicio.4 -->
        <tramo distancia="20.48"
                latitud="47° 13' 10.45'' N"
                longitud="14° 45' 45.85'' E"
                altitud="683"
                sector="1"/>

        <!-- Inicio.5 -->
        <tramo distancia="66.64"
                latitud="47° 13' 9.87'' N"
                longitud="14° 45' 42.79'' E"
                altitud="687"
                sector="1"/>

        <!-- Tramo 1 -->
        <tramo distancia="42.96"
                latitud="47° 13' 9.49'' N"
                longitud="14° 45' 40.85'' E"
                altitud="692"
                sector="1"/>
        
        <!-- Tramo 2 -->
        <tramo distancia="29.42"
                latitud="47° 13' 9.24'' N"
                longitud="14° 45' 39.52'' E"
                altitud="694"
                sector="1"/>

        <!-- Tramo 3 -->
        <tramo distancia="81.29"
                        latitud="47° 13' 10.22'' N" 
                        longitud="14° 45' 38.62'' E" 
                        altitud="696" 
                        sector="1"/>
                
        <!-- Tramo 4 -->
        <tramo distancia="134.71" 
                        latitud="47° 13' 12.39'' N" 
                        longitud="14° 45' 36.36'' E" 
                        altitud="698" 
                        sector="1"/>

        <!-- Tramo 4.1 -->
        <tramo distancia="134.71" 
                        latitud="47° 13' 12.93'' N" 
                        longitud="14° 45' 35.81'' E" 
                        altitud="699" 
                        sector="1"/>
        
        <!-- Tramo 5 -->
        <tramo distancia="98.24" 
                        latitud="47° 13' 15.94'' N" 
                        longitud="14° 45' 32.67'' E" 
                        altitud="699" 
                        sector="1"/>
         
        <!-- Tramo 6 -->
        <tramo distancia="122.13" 
                        latitud="47° 13' 18.65'' N" 
                        longitud="14° 45' 30.19'' E" 
                        altitud="700" 
                        sector="1"/>

        <!-- Tramo 6.1 -->
        <tramo distancia="122.13" 
                        latitud="47° 13' 21.065'' N" 
                        longitud="14° 45' 28.066'' E" 
                        altitud="701" 
                        sector="1"/>
        
        <!-- Tramo 7 -->
        <tramo distancia="44.48" 
                        latitud="47° 13' 22.02'' N" 
                        longitud="14° 45' 27.21'' E" 
                        altitud="701" 
                        sector="1"/>
                
        <!-- Tramo 8 -->
        <tramo distancia="71.11" 
                        latitud="47° 13' 23.05'' N" 
                        longitud="14° 45' 25.78'' E" 
                        altitud="703" 
                        sector="1"/>

        <!-- Tramo 8.1 -->
        <tramo distancia="71.11" 
                        latitud="47° 13' 24.006'' N" 
                        longitud="14° 45' 26.3556'' E" 
                        altitud="703" 
                        sector="1"/>
                
        <!-- Tramo 9 -->
        <tramo distancia="156.46" 
                        latitud="47° 13' 25.18'' N" 
                        longitud="14° 45' 26.92'' E" 
                        altitud="704" 
                        sector="1"/>
        
        <!-- Tramo 10 -->
        <tramo distancia="213.35" 
                        latitud="47° 13' 29'' N" 
                        longitud="14° 45' 22'' E" 
                        altitud="713" 
                        sector="1"/>
            
        <!-- Tramo 11 -->
        <tramo distancia="12.28" 
                        latitud="47° 13' 33.852'' N" 
                        longitud="14° 45' 14.7852'' E" 
                        altitud="741" 
                        sector="1"/>
        
        <!-- Tramo 12 -->
        <tramo distancia="17.17" 
                        latitud="47° 13' 34.25'' N" 
                        longitud="14° 45' 14.62'' E" 
                        altitud="744" 
                        sector="1"/>
        
        <!-- Tramo 13 -->
        <tramo distancia="90.52" 
                        latitud="47° 13' 34.58'' N" 
                        longitud="14° 45' 15.21'' E" 
                        altitud="745" 
                        sector="1"/>
                
        <!-- Tramo 13.1 -->
        <tramo distancia="55.78" 
                        latitud="47° 13' 34.91'' N" 
                        longitud="14° 45' 19.44'' E" 
                        altitud="746" 
                        sector="1"/>

        <!-- Tramo 14 -->
        <tramo distancia="77.88" 
                        latitud="47° 13' 35'' N" 
                        longitud="14° 45' 22'' E" 
                        altitud="745" 
                        sector="1"/>
                
         <!-- Tramo 15 -->               
        <tramo distancia="164.89" 
                        latitud="47° 13' 34.86'' N" 
                        longitud="14° 45' 25.26'' E" 
                        altitud="742" 
                        sector="2"/>
                
        <!-- Tramo 16 -->                
        <tramo distancia="168.48" 
                        latitud="47° 13' 33.91'' N" 
                        longitud="14° 45' 32.97'' E" 
                        altitud="734" 
                        sector="2"/>
                
        <!-- Tramo 17 -->                
        <tramo distancia="214.22"
                        latitud="47° 13' 33.02'' N"
                        longitud="14° 45' 40.90'' E"
                        altitud="727"
                        sector="2"/>

        <!-- Tramo 17.1 -->                
        <tramo distancia="214.22"
                        latitud="47° 13' 32.833'' N"
                        longitud="14° 45' 42.8364'' E"
                        altitud="726"
                        sector="2"/>

        <!-- Tramo 17.2 -->                
        <tramo distancia="214.22"
                        latitud="47° 13' 32.718'' N"
                        longitud="14° 45' 46.584'' E"
                        altitud="722"
                        sector="2"/>
                
        <!-- Tramo 18 -->                
        <tramo distancia="27.16" 
                        latitud="47° 13' 32.63'' N" 
                        longitud="14° 45' 51.12'' E" 
                        altitud="717" 
                        sector=""/>
                
        <!-- Tramo 19 -->               
        <tramo distancia="22.75" 
                        latitud="47° 13' 32.34'' N" 
                        longitud="14° 45' 52.46'' E" 
                        altitud="715" 
                        sector="2"/>
                
        <!-- Tramo 20 -->                
        <tramo distancia="21.68" 
                        latitud="47° 13' 31.59'' N" 
                        longitud="14° 45' 52.88'' E" 
                        altitud="714" 
                        sector="2"/>
                
        <!-- Tramo 21 -->                
        <tramo distancia="50.76" 
                        latitud="47° 13' 30.93'' N" 
                        longitud="14° 45' 52.51'' E" 
                        altitud="713" 
                        sector="2"/>
                
        <!-- Tramo 22 -->                
        <tramo distancia="45.55" 
                        latitud="47° 13' 29.62'' N" 
                        longitud="14° 45' 51.02'' E" 
                        altitud="711" 
                        sector="2"/>
                
        <!-- Tramo 23 -->                
        <tramo distancia="55.12" 
                        latitud="47° 13' 28.64'' N" 
                        longitud="14° 45' 49.41'' E" 
                        altitud="709"
